[build]
  command = "npm install && npm run build"
  publish = "dist"  # Replace 'dist' with your actual build directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define headers for all files in the built app
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# If using environment variables
# [build.environment]
#   MY_VARIABLE = "some value"
